### PR TITLE
Initial commit of Wp class

### PR DESCRIPTION
**Pull request by p810**
Initial commit of an implementation of `ParagonIE\Gossamer\DbInterface` that relies on an instance of `wpdb` (per #3).

I believe I followed the package's code style but if there's anything I missed or accidentally did differently let me know and I'll change it.

### CODE REVIEW

**Comment by p810** [comment]
It looks like Travis is failing on PHP > 5.6 because Psalm is reporting that none of `wpdb`s methods exist/assignments from calls to them are being inferred as mixed. I'm looking into this ATM.

**Comment by p810** [comment]
I was able to fix the Psalm errors by updating the stub for `wpdb`. I made this an abstract class and implemented the signatures of methods that `ParagonIE\Gossamer\Db\Wp` calls, which got rid of the `UndefinedMethod` and `MixedAssignment` errors, and maybe a couple others that were related to them. If there's a better way to handle this let me know and I'll update the PR.

**Review by paragonie-security — APPROVED** [review]

**Comment by paragonie-security** [comment]
Thanks a ton for writing this. It was next on our to-do list, and that means we can get `v0.1.0` out a lot sooner.

**Comment by p810** [comment]
> Thanks a ton for writing this. It was next on our to-do list, and that means we can get `v0.1.0` out a lot sooner.

I'm happy to help! I'm on vacation this week and needed something to do anyways.

**Pull request merged**
